### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by gecille87** [hana-magdy/root-finding-numerical-methods.#1]
Could you add a read me file on how to run and execute this? thanks

**Comment by gecille87** [comment]
A

> Could you add a read me file on how to run and execute this? thanks

A step by step instructions would be a great help. TY

**Comment by hana-magdy** [comment]
Download the whole project and run it on any python IDE.
The attached pdf contain sample runs and screenshots that will help you to use it.
[NumericalReport.pdf](https://github.com/hana-magdy/root-finding-numerical-methods./files/6562463/NumericalReport.pdf)
